// Code generated by vugu via vugugen DO NOT EDIT.
// Please regenerate instead of editing or add additional code in a separate file.

//go:build js && wasm

package main

import "fmt"
import "reflect"
import "github.com/vugu/vjson"
import "github.com/vugu/vugu/v2"
import "syscall/js"
import "log"

func (c *Radiobuttons) Build(vgin *vugu.BuildIn) (vgout *vugu.BuildOut) {

	vgout = &vugu.BuildOut{}

	var vgiterkey interface{}
	_ = vgiterkey
	var vgn *vugu.VGNode
	vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(3), Namespace: "", Data: "div", Attr: []vugu.VGAttribute{vugu.VGAttribute{Namespace: "", Key: "id", Val: "radiobuttons"}}}}
	vgout.Out = append(vgout.Out, vgn) // root for output
	{
		vgparent := vgn
		_ = vgparent
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(4), Data: " create the 4 radio buttons in the group, passing the properties we would nornmally set in JS as "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(4), Data: " fields in the underlying Go struct. The Language Radio Button can then read these fields to determine "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(4), Data: " if it is the selected default option. "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(4), Data: " In this case 'c' is the containing radio buttons not the language radio button itself "}}
		vgparent.AppendChild(vgn)
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		{
			vgcompKey := vugu.MakeCompKey(0x384A6757399E759C^vgin.CurrentPositionHash(), vgiterkey)
			// ask BuildEnv for prior instance of this specific component
			vgcomp, _ := vgin.BuildEnv.CachedComponent(vgcompKey).(*Languageradiobutton)
			if vgcomp == nil {
				// create new one if needed
				vgcomp = new(Languageradiobutton)
				vgin.BuildEnv.WireComponent(vgcomp)
			}
			vgin.BuildEnv.UseComponent(vgcompKey, vgcomp) // ensure we can use this in the cache next time around
			// vg-field = "Group=c"
			vgcomp.Group = c
			vgcomp.Id = "english"
			vgcomp.Value = "English"
			vgout.Components = append(vgout.Components, vgcomp)
			vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Component: vgcomp}}
			vgparent.AppendChild(vgn)
		}
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		{
			vgcompKey := vugu.MakeCompKey(0x681C96DAC00D87^vgin.CurrentPositionHash(), vgiterkey)
			// ask BuildEnv for prior instance of this specific component
			vgcomp, _ := vgin.BuildEnv.CachedComponent(vgcompKey).(*Languageradiobutton)
			if vgcomp == nil {
				// create new one if needed
				vgcomp = new(Languageradiobutton)
				vgin.BuildEnv.WireComponent(vgcomp)
			}
			vgin.BuildEnv.UseComponent(vgcompKey, vgcomp) // ensure we can use this in the cache next time around
			// vg-field = "Group=c"
			vgcomp.Group = c
			vgcomp.Id = "french"
			vgcomp.Value = "Français"
			vgout.Components = append(vgout.Components, vgcomp)
			vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Component: vgcomp}}
			vgparent.AppendChild(vgn)
		}
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		{
			vgcompKey := vugu.MakeCompKey(0x8572281BC9C26CD8^vgin.CurrentPositionHash(), vgiterkey)
			// ask BuildEnv for prior instance of this specific component
			vgcomp, _ := vgin.BuildEnv.CachedComponent(vgcompKey).(*Languageradiobutton)
			if vgcomp == nil {
				// create new one if needed
				vgcomp = new(Languageradiobutton)
				vgin.BuildEnv.WireComponent(vgcomp)
			}
			vgin.BuildEnv.UseComponent(vgcompKey, vgcomp) // ensure we can use this in the cache next time around
			// vg-field = "Group=c"
			vgcomp.Group = c
			vgcomp.Id = "italian"
			vgcomp.Value = "Italiano"
			vgout.Components = append(vgout.Components, vgcomp)
			vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Component: vgcomp}}
			vgparent.AppendChild(vgn)
		}
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n    "}}
		vgparent.AppendChild(vgn)
		{
			vgcompKey := vugu.MakeCompKey(0xC654B618B6455589^vgin.CurrentPositionHash(), vgiterkey)
			// ask BuildEnv for prior instance of this specific component
			vgcomp, _ := vgin.BuildEnv.CachedComponent(vgcompKey).(*Languageradiobutton)
			if vgcomp == nil {
				// create new one if needed
				vgcomp = new(Languageradiobutton)
				vgin.BuildEnv.WireComponent(vgcomp)
			}
			vgin.BuildEnv.UseComponent(vgcompKey, vgcomp) // ensure we can use this in the cache next time around
			// vg-field = "Group=c"
			vgcomp.Group = c
			vgcomp.Id = "german"
			vgcomp.Value = "Deutsch"
			vgout.Components = append(vgout.Components, vgcomp)
			vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Component: vgcomp}}
			vgparent.AppendChild(vgn)
		}
		vgn = &vugu.VGNode{VGNodeCommonCore: vugu.VGNodeCommonCore{Type: vugu.VGNodeType(1), Data: "\n\n"}}
		vgparent.AppendChild(vgn)
	}
	return vgout
}

// 'fix' unused imports
var _ fmt.Stringer
var _ reflect.Type
var _ vjson.RawMessage
var _ js.Value
var _ log.Logger
